In [4]:
import numpy as np # math calcuations and other matrix, vector processing
import pandas as pd # dataframe organization 
import seaborn as sns # for plotting
import matplotlib.pyplot as plt # for plotting

In [5]:
# load training data≠
df_train = pd.read_csv('bank.csv')

# load test data
df_test = pd.read_csv('bank.csv')

In [6]:
df_train

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  previous   y  
0     cellular   19   oct        79         1         0  no  
1     cellular   11   may       220         1         4  no  
2     cellular   16   apr       185         1         1  no  
3      unknown    3   jun       199         4         0  no  
4      unknown    5   may       226         1         0  no  
...        ...  ...   ...       ...       ...       ...  ..  
4516  cellular   30   jul       329         5         0  no  
4517   unknown    9   may       153         1         0  no  
4518  cellular   19   aug       151        11         0  no  
4519  cellular    6   feb       129         4         3  no  
4520  cellular    3   apr       345         2         7  no  

[4521 rows x 15 columns]

In [7]:
feature_drops = ['job','marital','education','default','housing','loan','contact','month','y']
df_train.drop(feature_drops, axis=1, inplace=True)
df_test.drop(feature_drops, axis=1, inplace=True)

In [14]:
X_train = df_train.drop(['balance'], axis=1).values

In [15]:
y_train = df_train['balance'].values

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
reg = LinearRegression()

In [18]:
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
reg.coef_

array([23.8308762 , -1.73314566, -0.19570159, -7.91290804, 46.13453232])

In [21]:
reg.intercept_

517.8536332684334

In [24]:
X_test = df_test.drop(['balance'], axis=1).values

In [25]:
y_pred = reg.predict(X_test)

In [26]:
y_pred

array([1176.4768179 , 1418.77881668, 1326.22079952, ..., 1726.69088031,
       1256.22575238, 1800.81161016])

In [27]:
import scipy.stats as stats

In [32]:
a=reg.coef_
a

array([23.8308762 , -1.73314566, -0.19570159, -7.91290804, 46.13453232])

In [35]:
np.var(a, ddof=1)

509.7478008898745

In [38]:
fdistribution = stats.f(len(a)-1,len(b)-1)

In [40]:
f_critical1 = fdistribution.ppf(0.025)
f_critical2 = fdistribution.ppf(0.975)

In [42]:
p_value = 2*min(fdistribution.cdf(f_critical1), 1-fdistribution.cdf(f_critical2))

In [43]:
print(fstatistics,f_critical1, f_critical2 )

0.04621072088724584 0.1123004778026619 4.718078458128192


In [44]:
if (p_value<0.05):
    print('Reject H0', p_value)
else:
    print('Cant Reject H0', p_value)

Cant Reject H0 0.05000000000000003
